import type { InteractionDefinition } from '../systems/interactions/interactionTypes';

export const interactions: InteractionDefinition[] = [
  {
    id: 'hub-guide-info',
    kind: 'info',
    title: 'M. Laurent',
    speaker: 'M. Laurent',
    body: [
      "Bienvenue à ISPA. Aujourd'hui, tout s'enchaîne vite : affichage, secrétariat, bibliothèque, puis une urgence en ville.",
      'Dans le hall, chaque porte correspond à une mission. Le tableau au centre rappelle ton avancement.',
    ],
  },
  {
    id: 'm1-ask-lina',
    kind: 'choice',
    context: "Hall d'entrée d'ISPA",
    speaker: 'Lina',
    prompt: 'Quelle est la meilleure façon de demander où vérifier la salle ?',
    options: [
      {
        id: 'm1-ask-lina-correct',
        text: 'Bonjour, excuse-moi, tu sais où est la salle B12 ?',
        feedback: "Oui, le panneau d'affichage est près de l'escalier.",
        penaltySeconds: 0,
      },
      {
        id: 'm1-ask-lina-rude',
        text: "Hé, B12, c'est par où ?",
        feedback: "Compréhensible, mais trop brusque pour commencer l'échange.",
        penaltySeconds: 8,
      },
      {
        id: 'm1-ask-lina-grammar',
        text: 'Bonjour, vous sais où est la salle B12 ?',
        feedback: "Attention : avec 'vous', on dit 'vous savez'.",
        penaltySeconds: 10,
      },
    ],
    correctOptionId: 'm1-ask-lina-correct',
    explanation: "Entre étudiants, une formule simple et polie suffit. L'erreur avec 'vous sais' n'est pas correcte.",
    retryOnIncorrect: true,
    successText: "Lina t'indique le panneau d'affichage au fond du hall.",
    metadata: {
      cefr: 'B1',
      skillType: 'speaking',
      linguisticFocus: 'demander un renseignement',
      registerFocus: 'poli mais naturel',
      missionId: 'hall-notice',
      tags: ['direction', 'campus', 'hall'],
    },
  },
  {
    id: 'm1-read-board',
    kind: 'choice',
    context: "Panneau d'affichage d'ISPA",
    prompt: "Quel avis concerne ton groupe aujourd'hui ?",
    options: [
      {
        id: 'm1-read-board-correct',
        text: 'Groupe B1 - Salle B12 déplacée en C4 à 9 h 30.',
        feedback: "C'est bien l'information utile pour ton cours.",
        penaltySeconds: 0,
      },
      {
        id: 'm1-read-board-library',
        text: 'Bibliothèque - Horaires modifiés mercredi.',
        feedback: "Cet avis est réel, mais il ne concerne pas ton cours.",
        penaltySeconds: 7,
      },
      {
        id: 'm1-read-board-club',
        text: "Atelier culture - Inscriptions à l'accueil.",
        feedback: "Ce n'est pas le bon avis. Cherche le niveau B1 et le changement de salle.",
        penaltySeconds: 7,
      },
    ],
    correctOptionId: 'm1-read-board-correct',
    explanation: "Sur un panneau, il faut repérer les mots-clés utiles : groupe, salle, changement.",
    retryOnIncorrect: true,
    successText: 'Le cours a été déplacé en salle C4.',
    metadata: {
      cefr: 'B1',
      skillType: 'reading',
      linguisticFocus: "lire un affichage institutionnel",
      registerFocus: 'information neutre',
      missionId: 'hall-notice',
      tags: ['notice-board', 'room-change'],
    },
  },
  {
    id: 'm1-wrong-door-info',
    kind: 'info',
    title: 'Salle fermée',
    body: [
      "Cette porte n'est plus la bonne. Le panneau indiquait un changement de salle.",
    ],
  },
  {
    id: 'm2-pick-document',
    kind: 'choice',
    context: 'Meuble de documents',
    prompt: 'Quel document dois-tu remettre au secrétariat ?',
    options: [
      {
        id: 'm2-pick-document-correct',
        text: "Attestation d'assurance",
        feedback: "Oui, c'est bien le document demandé.",
        penaltySeconds: 0,
      },
      {
        id: 'm2-pick-document-transport',
        text: 'Carte de transport',
        feedback: "Utile pour se déplacer, mais ce n'est pas un document pour le secrétariat ici.",
        penaltySeconds: 8,
      },
      {
        id: 'm2-pick-document-schedule',
        text: 'Planning du semestre',
        feedback: "Ce document informe sur les cours, mais il ne remplace pas une attestation.",
        penaltySeconds: 8,
      },
    ],
    correctOptionId: 'm2-pick-document-correct',
    explanation: "Il faut distinguer un document administratif précis d'un papier simplement plausible.",
    retryOnIncorrect: true,
    successText: "Tu prends l'attestation d'assurance.",
    metadata: {
      cefr: 'B1',
      skillType: 'reading',
      linguisticFocus: 'identifier un document',
      registerFocus: 'administratif',
      missionId: 'secretariat-delivery',
      tags: ['documents', 'administration'],
    },
  },
  {
    id: 'm2-secretary-greeting',
    kind: 'choice',
    context: "Accueil du secrétariat",
    speaker: 'Mme Claire',
    prompt: 'Quelle formulation convient le mieux au secrétariat ?',
    options: [
      {
        id: 'm2-secretary-greeting-correct',
        text: "Bonjour madame, je viens déposer mon attestation d'assurance au secrétariat.",
        feedback: "Très bien, la demande est claire et polie.",
        penaltySeconds: 0,
      },
      {
        id: 'm2-secretary-greeting-vague',
        text: 'Bonjour, je viens pour ça.',
        feedback: "C'est poli, mais trop vague dans un contexte administratif.",
        penaltySeconds: 8,
      },
      {
        id: 'm2-secretary-greeting-rude',
        text: "Tenez, c'est mon papier.",
        feedback: "Ici, cette formulation est trop brusque et imprécise.",
        penaltySeconds: 10,
      },
    ],
    correctOptionId: 'm2-secretary-greeting-correct',
    explanation: "Avec l'administration, mieux vaut annoncer clairement l'objet de sa visite.",
    retryOnIncorrect: true,
    successText: "Mme Claire enregistre ton document sans hésiter.",
    metadata: {
      cefr: 'B1',
      skillType: 'speaking',
      linguisticFocus: 'formuler une demande administrative',
      registerFocus: 'formel neutre',
      missionId: 'secretariat-delivery',
      tags: ['secretariat', 'politesse'],
    },
  },
  {
    id: 'm3-ask-librarian',
    kind: 'choice',
    context: 'Accueil de la bibliothèque',
    speaker: 'M. Durand',
    prompt: "Comment demander l'aide du bibliothécaire ?",
    options: [
      {
        id: 'm3-ask-librarian-correct',
        text: "Bonjour, je cherche un manuel de français niveau B1. Vous pouvez m'aider ?",
        feedback: "Oui, les ressources FLE B1 sont au rayon 3.",
        penaltySeconds: 0,
      },
      {
        id: 'm3-ask-librarian-familiar',
        text: 'Salut, je veux un livre de français.',
        feedback: "Le sens est clair, mais c'est trop familier pour s'adresser au personnel.",
        penaltySeconds: 8,
      },
      {
        id: 'm3-ask-librarian-wrong',
        text: 'Bonjour, je cherche la salle des professeurs.',
        feedback: "Cette demande n'a pas le bon sens dans la situation.",
        penaltySeconds: 9,
      },
    ],
    correctOptionId: 'm3-ask-librarian-correct',
    explanation: "Une demande polie, précise et simple est la plus naturelle dans une bibliothèque.",
    retryOnIncorrect: true,
    successText: 'Le bibliothécaire te guide vers le bon rayon.',
    metadata: {
      cefr: 'B1',
      skillType: 'speaking',
      linguisticFocus: 'demander une ressource',
      registerFocus: 'neutre formel',
      missionId: 'library-support',
      tags: ['library', 'resource'],
    },
  },
  {
    id: 'm3-shelf-choice',
    kind: 'choice',
    context: 'Rayonnage de la bibliothèque',
    prompt: 'Quel rayon correspond à la ressource indiquée ?',
    options: [
      {
        id: 'm3-shelf-choice-correct',
        text: 'Rayon 3 - FLE B1 : grammaire et méthodes',
        feedback: "Oui, c'est le bon rayon pour ton manuel.",
        penaltySeconds: 0,
      },
      {
        id: 'm3-shelf-choice-novel',
        text: 'Rayon 5 - Romans policiers',
        feedback: "Ce rayon est réel, mais il ne correspond pas à une ressource de français B1.",
        penaltySeconds: 8,
      },
      {
        id: 'm3-shelf-choice-news',
        text: 'Rayon 1 - Journaux locaux',
        feedback: "Les journaux peuvent être utiles, mais ce n'est pas la ressource demandée.",
        penaltySeconds: 8,
      },
    ],
    correctOptionId: 'm3-shelf-choice-correct',
    explanation: "Il faut relier l'information orale donnée par le bibliothécaire au bon rayon.",
    retryOnIncorrect: true,
    successText: 'Tu récupères le manuel demandé.',
    metadata: {
      cefr: 'B1',
      skillType: 'reading',
      linguisticFocus: 'repérer une ressource',
      registerFocus: 'signalétique neutre',
      missionId: 'library-support',
      tags: ['shelf', 'resource', 'library'],
    },
  },
  {
    id: 'm4-read-message',
    kind: 'choice',
    context: 'Téléphone',
    prompt: 'Message reçu : "Cours déplacé à l’annexe 2 à 14 h. Passe d’abord prendre le dossier bleu à l’accueil extérieur." Que fais-tu ?',
    options: [
      {
        id: 'm4-read-message-correct',
        text: "Je prends d'abord le dossier bleu, puis je vais à l'annexe 2.",
        feedback: "Oui, tu respectes l'ordre indiqué dans le message.",
        penaltySeconds: 0,
      },
      {
        id: 'm4-read-message-direct',
        text: "Je vais directement à l'annexe 2 sans passer à l'accueil.",
        feedback: "Le lieu est bon, mais tu ignores la première consigne du message.",
        penaltySeconds: 10,
      },
      {
        id: 'm4-read-message-wrong',
        text: 'Je retourne au secrétariat principal.',
        feedback: "Ce n'est pas ce qui est demandé dans le message.",
        penaltySeconds: 10,
      },
    ],
    correctOptionId: 'm4-read-message-correct',
    explanation: "Dans un message urgent, l'ordre des actions est essentiel.",
    retryOnIncorrect: true,
    successText: "Tu as compris qu'il faut d'abord récupérer le dossier bleu.",
    metadata: {
      cefr: 'B1',
      skillType: 'reading',
      linguisticFocus: 'comprendre une consigne courte',
      registerFocus: 'pratique',
      missionId: 'city-urgency',
      tags: ['message', 'urgence', 'ordre'],
    },
  },
  {
    id: 'm4-ask-passerby',
    kind: 'choice',
    context: "Rue près d'ISPA",
    speaker: 'Nora',
    prompt: "Comment demander une confirmation rapidement mais poliment ?",
    options: [
      {
        id: 'm4-ask-passerby-correct',
        text: "Pardon, vous pouvez me confirmer où se trouve l'annexe 2, s'il vous plaît ?",
        feedback: "Bien sûr, prenez la rue à droite jusqu'au bâtiment en briques.",
        penaltySeconds: 0,
      },
      {
        id: 'm4-ask-passerby-direct',
        text: "C'est où, l'annexe 2 ?",
        feedback: "Compréhensible, mais trop direct dans la rue avec une inconnue.",
        penaltySeconds: 8,
      },
      {
        id: 'm4-ask-passerby-grammar',
        text: 'Vous pouvez me confirme où est annexe 2 ?',
        feedback: "Attention : on dit 'confirmer' et 'où se trouve l'annexe 2'.",
        penaltySeconds: 10,
      },
    ],
    correctOptionId: 'm4-ask-passerby-correct',
    explanation: "Une demande polie et précise permet d'obtenir une réponse plus vite.",
    retryOnIncorrect: true,
    successText: "Nora te confirme la bonne direction.",
    metadata: {
      cefr: 'B1',
      skillType: 'speaking',
      linguisticFocus: 'demander une confirmation',
      registerFocus: 'poli',
      missionId: 'city-urgency',
      tags: ['city', 'clarification'],
    },
  },
  {
    id: 'm4-pick-folder',
    kind: 'choice',
    context: 'Accueil extérieur',
    prompt: 'Quel dossier dois-tu prendre ?',
    options: [
      {
        id: 'm4-pick-folder-correct',
        text: 'Le dossier bleu',
        feedback: "Oui, c'est exactement la couleur indiquée dans le message.",
        penaltySeconds: 0,
      },
      {
        id: 'm4-pick-folder-green',
        text: 'Le dossier vert',
        feedback: "Le message demandait le dossier bleu, pas le vert.",
        penaltySeconds: 7,
      },
      {
        id: 'm4-pick-folder-red',
        text: 'Le dossier rouge',
        feedback: "Le bon repère était la couleur bleue.",
        penaltySeconds: 7,
      },
    ],
    correctOptionId: 'm4-pick-folder-correct',
    explanation: "Dans un contexte urgent, il faut retenir les repères pratiques essentiels.",
    retryOnIncorrect: true,
    successText: 'Tu récupères le dossier bleu.',
    metadata: {
      cefr: 'B1',
      skillType: 'reading',
      linguisticFocus: 'identifier un objet précis',
      registerFocus: 'pratique',
      missionId: 'city-urgency',
      tags: ['folder', 'color', 'urgency'],
    },
  },
  {
    id: 'm4-final-formulation',
    kind: 'choice',
    context: 'Annexe 2',
    speaker: "Accueil de l'annexe",
    prompt: "Quelle formulation permet d'expliquer la situation clairement ?",
    options: [
      {
        id: 'm4-final-formulation-correct',
        text: "Bonjour, je viens pour le changement de salle et j'ai le dossier bleu demandé.",
        feedback: "Parfait, tout est clair. La salle de remplacement est prête.",
        penaltySeconds: 0,
      },
      {
        id: 'm4-final-formulation-vague',
        text: 'Je suis là pour la salle.',
        feedback: "Le message est trop vague dans une situation administrative urgente.",
        penaltySeconds: 8,
      },
      {
        id: 'm4-final-formulation-familiar',
        text: "Salut, j'ai un truc pour vous.",
        feedback: "Ici, la formulation est trop familière et manque de précision.",
        penaltySeconds: 10,
      },
    ],
    correctOptionId: 'm4-final-formulation-correct',
    explanation: "Dans l'urgence, une formulation polie et précise fait gagner du temps.",
    retryOnIncorrect: true,
    successText: "L'accueil ouvre immédiatement la bonne salle.",
    metadata: {
      cefr: 'B1',
      skillType: 'speaking',
      linguisticFocus: 'expliquer le motif de sa venue',
      registerFocus: 'administratif',
      missionId: 'city-urgency',
      tags: ['annex', 'urgency', 'administration'],
    },
  },
];

