import type { MissionDefinition } from '../systems/missions/missionTypes';

export const missions: MissionDefinition[] = [
  {
    id: 'hall-notice',
    order: 1,
    title: "Mission 1 : Panneau d'affichage",
    shortTitle: 'Panneau',
    brief: "Tu arrives à ISPA. Le cours de B1 a changé de salle. Parle à un étudiant, lis le bon avis et rejoins la salle avant le début du cours.",
    successSummary: "Tu as trouvé la bonne salle à temps et compris l'information utile.",
    failureSummary: "Le cours a commencé sans toi. Il fallait repérer le bon avis plus vite.",
    locationId: 'ispa-hall',
    timeLimitSeconds: 110,
    objectives: [
      {
        id: 'ask-student',
        kind: 'talk',
        label: 'Demande à un autre étudiant où vérifier le changement de salle.',
        targetId: 'm1-student-lina',
      },
      {
        id: 'read-board',
        kind: 'inspect',
        label: "Consulte le bon avis sur le panneau d'affichage.",
        targetId: 'm1-board',
      },
      {
        id: 'reach-classroom',
        kind: 'reach',
        label: 'Rejoins maintenant la salle C4.',
        targetId: 'm1-zone-c4',
      },
    ],
    learnedPoints: [
      "Demander un renseignement simplement mais poliment à un autre étudiant.",
      "Repérer l'information utile sur un panneau institutionnel.",
      "Comprendre un changement de salle sans se laisser distraire par les autres avis.",
    ],
    vocabularyIds: ['salle', 'panneau-affichage', 'premier-etage'],
    nextMissionId: 'secretariat-delivery',
  },
  {
    id: 'secretariat-delivery',
    order: 2,
    title: 'Mission 2 : Document au secrétariat',
    shortTitle: 'Secrétariat',
    brief: "Le secrétariat attend ton attestation d'assurance. Choisis le bon document, rejoins l'accueil et formule ta demande correctement.",
    successSummary: "Le document a été déposé correctement et ta formulation était adaptée à l'administration.",
    failureSummary: "Le document n'a pas été remis à temps. Il fallait choisir le bon papier et parler plus précisément.",
    locationId: 'secretariat-wing',
    timeLimitSeconds: 130,
    objectives: [
      {
        id: 'pick-document',
        kind: 'collect',
        label: "Récupère l'attestation d'assurance sur le meuble de documents.",
        targetId: 'm2-tray',
      },
      {
        id: 'deliver-document',
        kind: 'deliver',
        label: "Remets l'attestation d'assurance à la réception du secrétariat.",
        targetId: 'm2-secretary',
        requiredItemId: 'insurance-certificate',
      },
    ],
    learnedPoints: [
      "Identifier un document administratif parmi plusieurs papiers plausibles.",
      "Préciser l'objet de sa visite au secrétariat avec une formule polie.",
    ],
    vocabularyIds: ['attestation-assurance', 'secretariat', 'deposer-document'],
    nextMissionId: 'library-support',
  },
  {
    id: 'library-support',
    order: 3,
    title: 'Mission 3 : Ressource à la bibliothèque',
    shortTitle: 'Bibliothèque',
    brief: "Tu dois trouver une ressource de français B1. Lis les panneaux, demande de l'aide et choisis le bon rayon.",
    successSummary: "Tu as trouvé la bonne ressource et formulé ta demande de manière naturelle.",
    failureSummary: "Tu n'as pas récupéré la bonne ressource à temps. Il fallait mieux suivre les indices.",
    locationId: 'library-floor',
    timeLimitSeconds: 140,
    objectives: [
      {
        id: 'ask-librarian',
        kind: 'talk',
        label: "Demande au bibliothécaire où se trouvent les ressources de français B1.",
        targetId: 'm3-librarian',
      },
      {
        id: 'collect-manual',
        kind: 'collect',
        label: 'Va au bon rayon et prends le manuel indiqué.',
        targetId: 'm3-shelf',
      },
    ],
    learnedPoints: [
      "Demander une information à un membre du personnel avec un registre adapté.",
      "Comprendre une orientation interne simple dans une bibliothèque.",
    ],
    vocabularyIds: ['bibliotheque', 'rayon', 'manuel-b1'],
    nextMissionId: 'city-urgency',
  },
  {
    id: 'city-urgency',
    order: 4,
    title: "Mission 4 : Urgence en ville",
    shortTitle: 'Urgence',
    brief: "Un message annonce un changement urgent. Comprends la consigne, demande une confirmation, récupère le dossier bleu et rejoins l'annexe 2.",
    successSummary: "Tu as géré l'urgence, suivi les bonnes étapes et obtenu l'information utile rapidement.",
    failureSummary: "L'urgence n'a pas été résolue à temps. Il fallait mieux interpréter le message et garder le bon ordre d'actions.",
    locationId: 'amiens-outdoor',
    timeLimitSeconds: 155,
    objectives: [
      {
        id: 'read-message',
        kind: 'choose',
        label: "Comprends d'abord le message reçu sur ton téléphone.",
        targetId: 'm4-phone',
      },
      {
        id: 'ask-passerby',
        kind: 'talk',
        label: "Demande à une passante où se trouve l'annexe 2.",
        targetId: 'm4-passerby',
      },
      {
        id: 'pick-folder',
        kind: 'collect',
        label: "Récupère le bon dossier à l'accueil extérieur.",
        targetId: 'm4-locker',
      },
      {
        id: 'reach-annex',
        kind: 'deliver',
        label: "Présente-toi à l'annexe 2 avec le dossier bleu.",
        targetId: 'm4-annex-desk',
        requiredItemId: 'blue-folder',
      },
    ],
    learnedPoints: [
      "Comprendre un message pratique court et en suivre l'ordre logique.",
      "Demander une confirmation polie dans la rue.",
      "Présenter clairement la raison de sa venue dans une situation urgente.",
    ],
    vocabularyIds: ['annexe', 'dossier-bleu', 'confirmer'],
  },
];

